branches:
  only:
    - master

configuration: Release

init:
  - git config --global core.autocrlf true

before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore
  
build:
  project: Wyam.sln
  publish_nuget: true

test:
  categories:
    except:
      - ExcludeFromAppVeyor
  
artifacts:
  - path: Wyam\bin\Release
    name: Wyam
  - path: '**\Wyam.*.nupkg'
 
deploy:
  provider: NuGet
  api_key:
    secure: amWULnZVsv5qbKalO9tM+5OvexyHcd36bp/t9D79yjaA/A5LVx+Uho7MG90d3/Bf
  artifact: /.*\.nupkg/
  
on_failure:
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"
